title: Tauki Talks
description: Personal website and blog

url: "https://tauki.site" # your custom domain
author:
  name: Tauki Tahmid

# Prose Journal Settings
prose_categories:
  - prose
  - story
  - poem

# Build settings
markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-seo-tag

feed:
  collections:
    - notes

collections:
  notes:
    output: true
    permalink: /notes/:slug/

defaults:
  - scope:
      path: ""
      type: "notes"
    values:
      layout: "default"


# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - _notes/assets/
  - to_process/